### ISSUE TITLE
A small vocabulary for data transfer

### ISSUE THREAD

**Issue by SamPenrose** [slightlyoff/BackgroundSync#16]
Several observers have noted that different "use cases" want very different behavior from the system -- an email app versus a movie player, for example. This diversity of needs might be easier to discuss if we had a small vocabulary for discussing it. For example:

- structured records (emails, contacts) vs blobs (video)
- "small" vs "large" relative to cellular bandwidth and device storage
- user prioritized (a message fired with "Send" or "Send when online")

**Comment by annevk** [comment]
So that kind of API seems like something we could perhaps offer separately. E.g.

    fetchInBackground(...)

which would be available in service workers, simply returns, and when done fires an event at the service worker (perhaps booting it up if it was shut down).

That does not seem to require a change in the synchronization API necessarily.

**Comment by jkarlin** [comment]
+1 to a separate API for background downloads/uploads.
