### ISSUE TITLE
Should SyncRegistrationOptions.data be more than a DOMString?

### ISSUE THREAD

**Issue by clelland** [slightlyoff/BackgroundSync#26]
Since this is a JavaScript API, should clients be allowed so store arbitrary JavaScript objects in the `data` field of a SyncRegistrationOptions object?

Certainly it needs to be serializable, since this data will have to outlive the process which registers it, so we can't support storing open file handles or message ports, for instance. It seems like anything which is JSON-serializable should be allowed, and ideally the API could support anything which could also be serialized by, say, IndexedDB.

Should we extend this to allow more than a single string?

**Comment by annevk** [comment]
https://notifications.spec.whatwg.org/ uses structured cloning. That's probably what we want to use everywhere where objects make sense.

**Comment by jkarlin** [comment]
I'm thinking that we should actually just remove the data parameter and have developers use indexeddb instead. Why deal with (potentially large) data storage in sync when we already have a mechanism for that. This lets developers easily coalesce syncs, like so:

You create a tweet offline, store the data in indexeddb, and register a one-shot for it. After creating a second tweet offline store it, one-shot registration with the same id fails because it's already registered. When the event is fired, send all of the stored tweets.

**Comment by annevk** [comment]
Since we removed data, someone should close this.
