### ISSUE TITLE
Should the ID be auto-generated by default?

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#41]
@annevk @clelland @jakearchibald 

As of ccdb392126ca4e8b41ddfc7685a1f0603ce258b8 the id can be default set by the UA. After some thought, I don't like the idea of a default id.

1) What are the use cases for a default id? I can only think of calendar events, and we're not (currently) supporting exact timers anyway. And even for a calendar, you could compose an id based on the name and time of the event. This would also help to prevent duplicate registrations.

2) Default id makes it easy to accidentally double register. Imagine the page registers a repeating sync each time it's opened. If it had to use the same id each time the registration would reject.

**Comment by KenjiBaheux** [comment]
I think a nice side effect of this is that it makes the id argument optional which in turn help minimize the surface needed to start solving actual use cases (id as a parameter and id as an attribute of a ServiceWorkerSyncRegistration could come later). See https://github.com/slightlyoff/BackgroundSync/issues/42

**Comment by jkarlin** [comment]
The risk of people repeatedly registering for the same event is really high. I agree that it's not required for the MVP mentioned in #42 but the plan is to quickly most past MVP and I don't want to introduce default IDs to support a transition state.

**Comment by KenjiBaheux** [comment]
2) Default id makes it easy to accidentally double register. Imagine the page registers a repeating sync each time it's opened. If it had to use the same id each time the registration would reject.

This happens because the UA would generate a unique id if none is specified. What if instead of that, the UA would assign a non unique default id (e.g. id === null)? 
Benefits:
 - if you only have one use case for onsync you don't really need an id
 - you don't have to check for the existence of a previous registration to avoid duplicate registrations*

*: sidenote, I don't think rejecting duplicate registrations is the right thing to do. I will file a separate issue explaining my rationale.

**Comment by annevk** [comment]
@KenjiBaheux ah, I just had the same thought, though I would pick the empty string. However, it's still unclear to me why the one-off wake-when-online use case requires an ID to begin with.

**Comment by jkarlin** [comment]
I could see having an empty string as a default id. I like that it simplifies the MVP.
