### ISSUE TITLE
More opportunities for BG sync to outperform self-made solutions (e.g. robustness of onsync)

### ISSUE THREAD

**Issue by KenjiBaheux** [slightlyoff/BackgroundSync#59]
Here is one thing that came out while talking to folks interested in this API.

Ignoring BG sync's ability to outrun the life of the web app, these folks had implemented something similar to "background sync".

When offline, they let their users perform some basic operations in their web app (e.g. delete an item). Ideally, when the user comes back online these operations are synchronized with the server. 

In practice, they apply an exponential backoff to the synchronization operation. This helps them deal with various conditions: from offline (despite say navigator.online being true) to kind of online and up to server issues (e.g. 500).

Are there opportunities for bg sync to do a better job here?
 1. take care of the exponential backoff strategy => I think this is already on the map since it's mentioned in the explainer.
 2. have onsync be a more robust signal that the user is truly back online with optionally some extra guarantees about the quality of the connection (e.g. not "kind of online") and the reachability of specific endpoints. This seems quite desirable given that it could make bg sync even more power friendly.

Perhaps, a lot of that might simply be UA optimizations. Then, depending on what we learn, we might want to look into offering more flexibility in v2.

Thoughts?

**Comment by annevk** [comment]
It may be an idea to have a third API variant that does not show UI and can be used to minimize battery usage by the application. If the application remains running, it can use this API to determine when it can synchronize again, without asking the user for permission since it expects to keep running anyway.

Alternatively user agents could implement this as a variant of the one-off variant and only prompt the user for permission when they close the application.

**Comment by KenjiBaheux** [comment]
I like the suggestion of making this a User Agent side variant of the one-off.
I think the other suggestions are indeed User Agent optimizations (e.g. minimize "dud" onsync).
