### ISSUE TITLE
Firing onsync and register/unregister

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#62]
If register or unregister is called in onsync on the firing sync's id, what is the effect on the backoff mechanism?

Scenario 1: During onsync, the id is unregistered but waitUntil rejects. Do we try again later with the backoff mechanism or stop?

Scenario 2: During onsync, the id is overwritten but waitUntil rejects. Do we try again later with the backoff mechanism or stop? If we try again later, do we try again with the original registration's parameters or the new one's?

**Comment by jkarlin** [comment]
Here is my first take: Once an event is fired, it should run (with the same parameters) until completion or the backoff mechanism gives up. If you want to cancel it, then don't reject the waitUntil. If you overwrite it, then that will only alter future firings. Also, the overwritten registration should not get to fire until the old registration has finished firing.

**Comment by jakearchibald** [comment]
My first take:

> Scenario 1: During onsync, the id is unregistered but waitUntil rejects. Do we try again later with the backoff mechanism or stop?

Even in one-off, the registration should remain during the sync event. For one-off, the registration is automatically unregistered if:

* Event callbacks complete and none call `.waitUntil`
* All promises passed to `.waitUntil` fulfill

`.unregister` forces unregistration, if I call that I wouldn't expect a later retry, even if a `.waitUntil` promise rejects.

How periodic syncs handle rejections to `waitUntil` is going to be a little more complicated, I'm further convinced we should treat them completely separate. 

> Scenario 2: During onsync, the id is overwritten but waitUntil rejects. Do we try again later with the backoff mechanism or stop? If we try again later, do we try again with the original registration's parameters or the new one's?

I'm assuming that push registration properties are immutable? If id is treated like 'tag' (https://github.com/slightlyoff/BackgroundSync/issues/64) then it can't be overwritten. Other properties can though, by calling `.register` with the same tag.

If we cut down the options for one-off down to just id/tag, then there isn't a problem here. For periodic, I think the retry should take the new values for battery, network & idle into account. Changes to 'period' probably don't apply because a period sync's "retry" is outside of the period system anyway.

**Comment by jkarlin** [comment]
The spec has what Jake suggests.
