### ISSUE TITLE
Do we need minDelay & maxDelay?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#67]
What are their use-cases?

`minDelay` - for periodic syncs I think the `minPeriod` would be the min delay. Is there a case you'd want them to be different?

`maxDelay` - given https://github.com/slightlyoff/BackgroundSync/issues/35#issuecomment-86940721, I don't think we'd want to allow this.

**Comment by jkarlin** [comment]
These are the parameters that differentiate between, "sync runs whenever the hell the UA wants" and "sync runs when the user/developer wants". I think for a first (MVP) draft we'll stick with the former. But it really does hamper use cases.

One use of `maxDelay` is to allow a timer to start conservative but get more aggressive over time. E.g. I'll try waiting for charging on wifi for two hours, but after that point I'll settle for charging and cellular, and after that I'll take anything because the data is getting stale.

The purpose of `minDelay` is to set a start time. E.g., the user would like to sync around 5am every morning before getting on the train so set `minDelay` to a value that reaches 4am and `minPeriod` to 24 hours.

**Comment by jkarlin** [comment]
Note that min and max delay come from Android's [JobScheduler](https://developer.android.com/reference/android/app/job/JobInfo.Builder.html#JobInfo.Builder(int, android.content.ComponentName)).

**Comment by jkarlin** [comment]
Not in the spec.
