### ISSUE TITLE
Feedback about the API name "Background Sync"

### ISSUE THREAD

**Issue by KenjiBaheux** [slightlyoff/BackgroundSync#76]
We had a Service Worker and related APIs hackathon in Tokyo last week.
Going around the tables, I explained about upcoming work including Background Sync.

The takeaway is that almost everyone was excited about what Background Sync would let them do but were puzzled by the name. They assumed that the API was **specifically** designed for dealing with synchronizing client-server data sources. Some folks suggested "Background Task".

Thoughts?

**Comment by annevk** [comment]
iOS calls this "Background App Refresh" (also to end users). What's the Android term?

**Comment by KenjiBaheux** [comment]
JobScheduler: https://developer.android.com/reference/android/app/job/JobScheduler.html

**Comment by annevk** [comment]
So "Task" is used by HTML already and "Job" is used by JavaScript (mistakenly, imo, but it's there). Maybe "Background Script"?

**Comment by jakearchibald** [comment]
`.backgroundScript.register` sounds like I'd provide a separate script to the serviceworker.

Although "task" is used by HTML, does it still kinda make sense? Isn't firing an event a task in HTML?

**Comment by jkarlin** [comment]
+1 for task

**Comment by annevk** [comment]
I think "background task" is too generic (what I suggested was too). E.g. "push" is technically a "background task" too, but a lot more clear.

The one-off event is mostly about "when online", the periodic event is mostly about keeping data fresh. Background networking doesn't sound too great unfortunately, but sync mostly has those implications.

And the API is sort of designed for synchronizing client-server resources. Is there any actual problem here?

**Comment by KenjiBaheux** [comment]
With the use cases mentioned in https://github.com/slightlyoff/BackgroundSync/issues/77 the synchronizing aspect is less obvious.
 
The Background Task API available to Windows Store Apps is addressing similar needs:
http://visualstudiomagazine.com/articles/2013/05/01/background-tasks-in-windows-store-apps.aspx

**Comment by jkarlin** [comment]
This can be bikeshed forever. Until something drastically better comes along let's stick with sync.
