### ISSUE TITLE
"last chance"

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#83]
The Chrome implementation is likely to give up on a one-off sync at some point, I wonder if other vendors will want the same.

We may want to expose this to the developer, in the form of something like `syncEvent.lastChance`. As a developer, I would do…

```js
self.onsync = event => {
  event.waitUntil(
    doSomeStuff().catch(err => {
      if (event.lastChance) showFailureNotification();
      throw err;
    })
  );
};
```

The failure notification would be something like "Failed to upload 12 photos". Tapping this would take the user back to the site, which could re-request the sync.

**Comment by wanderview** [comment]
When you say "give up on a one-off sync" you mean terminate a SW holding waitUntil() open too long?

**Comment by jakearchibald** [comment]
@wanderview sorry for the lack of detail, I mean cases where the browser will not retry, even if the sync fails.

If a sync is continually failing despite connectivity, would we want to grant the browser the ability to stop firing sync until the user revisits the site? Or would exponential backoff be enough? We need to be able to prevent people using this for bitcoin mining etc.

**Comment by annevk** [comment]
I think we plan on using exponential backoff, just as with push.

**Comment by jakearchibald** [comment]
Ok, filing this under "brainfart" unless there's better evidence that we need it

**Comment by jkarlin** [comment]
We do need to eventually delete the sync. We can't let it sit in the browser forever. Imagine you accidentally register 1 million sync events that all fail (because of programmer error). They would stay in browser memory *forever* if we didn't eventually delete them.

Besides which, the purpose of one-shots is to fire quickly. If I send an email and it doesn't go out for two weeks it's probably a bit late at that point. Not sure what the right point to give up is though. Perhaps once the exponential backoff reaches 24 hours?

side note: I'm wary of allowing the event handler to show a notification or open a window. That is a great opportunity for spam.

**Comment by jakearchibald** [comment]
> I'm wary of allowing the event handler to show a notification or open a window. That is a great opportunity for spam.

Perhaps, but we make it pretty easy to revoke that permission. Without it, this use case is gone https://www.youtube.com/watch?v=wjUCXgM70c0

(also, the Hangouts native app will show an "unable to send" notification if background-send fails)

**Comment by annevk** [comment]
Yeah, we should probably restrict what you can do from the callback. And that should be written down in detail. Note that our exponential backoff for push means that eventually we give up and remove the permission. I would expect the same here.

**Comment by jakearchibald** [comment]
Whatever we decide here we should do the same for push. Would be great if we could define it in one spec and reference from the other. Perhaps this should go in the extensibility part of the SW spec.

**Comment by jkarlin** [comment]
Getting back to the original topic of this thread, I agree that it would be useful to know: 
1. if this is the last retry attempt
2. how long the event is allowed to run for before the service worker intends to kill it*

* Chrome is going to put a cap on sync runtime per service worker registration while in the background. The time is reset on the next controlled page load.

**Comment by jkarlin** [comment]
Any objections to adding the number of retries left and the amount of time left to the sync event?

**Comment by mkruisselbrink** [comment]
Is there value in knowing the number of retries left, as opposed to just knowing if this is the last retry? It seems that only exposing a boolean would leave more room for user agents to figure out what behavior works best.

And for the time a worker can take to process an event, if that is something that a SW can usefully use, would that be something that would make more sense to be part of ExtendableEvent so it can be used in any event handler?

**Comment by jkarlin** [comment]
> Is there value in knowing the number of retries left, as opposed to just knowing if this is the last retry? It seems that only exposing a boolean would leave more room for user agents to figure out what behavior works best.

I suppose not, `event.lastChance` should suffice. Except..

> And for the time a worker can take to process an event, if that is something that a SW can usefully use, would that be something that would make more sense to be part of ExtendableEvent so it can be used in any event handler?

The purpose of revealing the time left was so that time could be budgeted. But I now realize how difficult that can be for the UA. What if there is no time limit when there is a controlled client? What if the time limit is reset when a controlled client is loaded? Perhaps we shouldn't expose time in the API.

We do still need to address what happens if the sync event runs out of time in a `waitUntil`. How is the client informed? I see three options: 

1. Add a callback to waitUntil that can be called shortly before killing the service worker due to timeout.
2. Instead of `event.lastChance` we have `event.failed` and when that is true there are only a few seconds for the event to run.
3. Create a new event, `onsyncfailed` which has a few seconds to run.

**Comment by jkarlin** [comment]
Current I think adding the `onsyncfailed` event is the way to go since it behaves differently from `onsync` (e.g. less time to run) and makes it clear to the developer what is happening.

**Comment by mkruisselbrink** [comment]
I'm not sure I agree that `onsyncfailed` is better than having an `event.lastChance` attribute. For one it seems the logic that determines when they fire would be different, where `onsyncfailed` would fire pretty much immediately after the last failed sync attempt, while a lastChance sync event would presumably fire with the same delay/exponential back-off all other sync attempts used. And I think that can be an important difference: one reason a sync can have failed is because we had to kill the service worker before it finished its sync; having to immediately launch the same service worker again to deliver the `onsyncfailed` event doesn't seem like what we'd always want to do.

Also I'm not sure what the value is in informing a service worker that syncing failed. In general a service worker should be assuming that a sync will fail, and only mark whatever data it is trying to sync as synced when the sync succeeds. And we don't need to add anything special to allow it to detect when sync succeeded. And if a SW wants to display a notification when sync failed, it can do that in a regular `event.lastChance` sync event just as well as it could in an `onsyncfailed` event. Worst case it loses one retry attempt by doing that (of course that would be pretty bad in a user agent that doesn't implement retry at all. So if we go that way the spec should probably require at least one retry attempt...)

Maybe some realistic sample code of how an actual website might be using sync would help to determine which lastChance/failed API style would be easier to use... Although I'm guessing one API would be better for some use cases while the other would be easier for other use cases.

**Comment by jkarlin** [comment]
The use case that I had in mind is notification of failure. Good point, the developer could use the "lastChance" round to display a notification and give up instead of trying one more time. That's nice and simple.

**Comment by jkarlin** [comment]
How might a UA invoke both a time limit and a retry cap? Say the first firing of an event has lastChance=false (because it's willing to retry 4 more times) but the event uses up all of the available time? Should it then fire again with lastChance=true and a short time budget?

We need to make it clear in the spec that the time that the event has to run is unknown and may be short (especially in the lastChange=true case).
