### ISSUE TITLE
Focus on one-shot syncs

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#92]
We've split periodic and one-shot background sync into two different APIs (SyncManager and PeriodicSyncManager). They're different enough that it seems worth focusing on one (namely one-shots) before moving our attention to periodic. This will simplify use-cases, discussion about permissions, and resource/privacy concerns.

**Comment by mkruisselbrink** [comment]
I agree that we should fully focus on one-shot syncs for now, and postpone any discussion related to periodic syncs. I'm not sure if that means we should actually remove any reference to periodic sync from explainers etc, since presumably this is still a feature that a future version of this spec is hoping to address. Of course we should make it clear what features exist/will exist in which versions of the spec.
But on the other hand I guess we can always revert the changes to remove periodic sync from the spec when we get to actually working on/thinking about it in the future.

**Comment by jkarlin** [comment]
Agreed. Leaving existing periodic discussions in place.

**Comment by mbrevda** [comment]
Is PeriodicSyncManager being discussed anywhere? I'd like follow an along
